### ISSUE TITLE
Error after sending text to the bot

### ISSUE THREAD

**Issue by Webslug** [mercm8/chat-llama-discord-bot#9]
Hey there,

The bot was working last night but when I goto run it today I am seeing the following errors in the console.

The bot is able to connect and load a model.

Can anyone help please?

ERROR [2023-05-26 08:20:36]: Ignoring exception in on_message (Line: 515 in on_error, client.py )
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Roaming\Python\Python310\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "D:\AI\oobabooga\text-generation-webui\bot.py", line 485, in on_message

**Comment by MuXodious** [comment]
Which ooba webui commit are you on?  Have installed all requirements? Have you created a character file specific to your bot?  I feel like that isn't the entire error log.

**Comment by mercm8** [comment]
looks like it's the one that showed up after the last ooba update

it's really kicking my ass atm

` ERROR [2023-05-27 16:29:05]: Ignoring exception in on_message (Line: 515 in on_error, client.py )
Traceback (most recent call last):
  File "F:\llm\test\installer_files\env\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "F:\llm\test\text-generation-webui\bot.py", line 508, in on_message
    await llm_gen(message, queues)
  File "F:\llm\test\text-generation-webui\bot.py", line 368, in llm_gen
    last_resp = chatbot_wrapper_wrapper(user_input)
  File "F:\llm\test\text-generation-webui\bot.py", line 346, in chatbot_wrapper_wrapper
    for resp in chatbot_wrapper(**user_input):
  File "F:\llm\test\text-generation-webui\modules\chat.py", line 238, in chatbot_wrapper
    for j, reply in enumerate(generate_reply(prompt + cumulative_reply, state, eos_token=eos_token, stopping_strings=stopping_strings, is_chat=True)):
  File "F:\llm\test\text-generation-webui\modules\text_generation.py", line 22, in generate_reply
    shared.generation_lock.acquire()
AttributeError: 'NoneType' object has no attribute 'acquire'
`

**Comment by mercm8** [comment]
Yep, got it. All it took was a shower.

**Comment by MuXodious** [comment]
Hey @mercm8! Thank you for working even in the shover. I'm currently facing the following error and couldn't fix it by fiddling around with files. I'm leaving it here.  


```
ERROR [2023-05-27 23:59:33]: Ignoring exception in on_ready (Line: 515 in on_error, client.py )
Traceback (most recent call last):
  File "/mnt/NVME2TB/text-generation-webui/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/NVME2TB/text-generation-webui/bot.py", line 397, in on_ready
    client.behavior.__dict__.update(data["behavior"])
KeyError: 'behavior'
ERROR [2023-05-27 23:59:42]: Ignoring exception in on_message (Line: 515 in on_error, client.py )
Traceback (most recent call last):
  File "/mnt/NVME2TB/text-generation-webui/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/NVME2TB/text-generation-webui/bot.py", line 506, in on_message
    if client.behavior.current_time:
AttributeError: 'Behavior' object has no attribute 'current_time'
```

PS. I'm keeping extensions branch up to date with main.  It's also suffering from this error.

**Comment by MuXodious** [comment]
Hey @mercm8! Thank you for working even in the shower. I'm currently facing the following error and couldn't fix it by fiddling around with files. I'm leaving it here.  


```
ERROR [2023-05-27 23:59:33]: Ignoring exception in on_ready (Line: 515 in on_error, client.py )
Traceback (most recent call last):
  File " /text-generation-webui/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/text-generation-webui/bot.py", line 397, in on_ready
    client.behavior.__dict__.update(data["behavior"])
KeyError: 'behavior'
ERROR [2023-05-27 23:59:42]: Ignoring exception in on_message (Line: 515 in on_error, client.py )
Traceback (most recent call last):
  File " /text-generation-webui/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File " /text-generation-webui/bot.py", line 506, in on_message
    if client.behavior.current_time:
AttributeError: 'Behavior' object has no attribute 'current_time'
```

PS. I'm keeping extensions branch up to date with main.  It's also suffering from this error.

**Comment by mercm8** [comment]
yeah I got too excited and forgot to set a base value for current_time

just add a current_time: 0 under behavior in character settings, should work for now

**Comment by MuXodious** [comment]
Oh yeah. I saw this line  `if current_time == 'now':`

**Comment by MuXodious** [comment]
Oh yeah. I saw this line,  ` if current_time == 'now':`, and added `current_time:'now'` to the character sheet, but totally forgot about trying an integer instead. Thank you again. It's good be excited 😇

**Comment by Fearblade66** [comment]
> The character files im using isnt working, what sites do you guys use for character files?

**Comment by MuXodious** [comment]
@Fearblade66 Pay attention to the format of character files on this repository. Character files (yaml and the picture) should have the same name as the bot. If there are any sites for premade character files (not just for this bot), I would be glad to learn as well.

**Comment by Fearblade66** [comment]
@MuXodious I found this website, seems to be the best i could find so far. [[[ NSFW warning ]]] https://booru.plus/+pygmalion

**Comment by MuXodious** [comment]
@Fearblade66 
![1640420779912](https://github.com/mercm8/chat-llama-discord-bot/assets/64381665/1653ef87-a1bb-4c69-b1d1-30d63fbb428d)
Thanks mate. Were you able to get your bot working?
